# Generated by Django 5.1.3 on 2024-11-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('date', 'Date'), ('number', 'Number'), ('checkbox', 'Checkbox')], max_length=50),
        ),
    ]
